### ISSUE TITLE
[Feature]:Order management system 

### ISSUE THREAD

**Issue by Ayushkumarsingh09** [OPCODE-Open-Spring-Fest/Quant#3]
### So, what is it about?

In the provided algorithm EMA crossover and Bollinger band strategy is used. 
Update it with a more sophisticated and accurate strategy for order managing.
Type- Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jagpreet153** [comment]
@Ayushkumarsingh09 Assign this task to me

**Comment by Ayushkumarsingh09** [comment]
Assigned, you can start.
